application: devfest-2015
version: 1
runtime: php55
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: app\favicon.ico
  upload: favicon\.ico
  
- url: /apple-touch-icon\.png
  static_files: app\apple-touch-icon.png
  upload: apple-touch-icon\.png

- url: /robots\.txt
  static_files: app\robots.txt
  upload: robots\.txt

- url: /img
  static_dir: img

- url: /manifest\.json
  static_files: manifest.json
  upload: manifest\.json

- url: /.well-known/acme-challenge/(.*)
  script: cert.php

- url: (.*)/
  static_files: app\1/index.html
  upload: app
  secure: always

- url: (.*)
  static_files: app\1
  upload: app
  secure: always