application: devfest-2015
version: 2
runtime: php55
threadsafe: true
api_version: 1

handlers:
- url: /.well-known/acme-challenge/(.*)
  script: cert.php

- url: (.*)/
  static_files: app\1/index.html
  upload: app/index.html
  secure: always

- url: /
  static_dir: app